### ISSUE TITLE
Fix Footer

### ISSUE THREAD

**Issue by tsanyqudsi** [ahsan2607/subway-surfers-imitation#10]
For now the mobile layout for footer is like this

![image](https://github.com/ahsan2607/subway-surfers-imitation/assets/1050880/f837f12d-94ce-4957-9442-ef0deb3e3d6a)

make it better.

**Comment by ahsan2607** [comment]
![Screenshot (400)](https://github.com/ahsan2607/subway-surfers-imitation/assets/103492143/16a18dbf-9dd0-4ce0-be6a-6fadf023355f)
Done
