### ISSUE TITLE
Delete most of the sidebar menu except home 

### ISSUE THREAD

**Issue by tsanyqudsi** [ahsan2607/subway-surfers-imitation#13]
![image](https://github.com/ahsan2607/subway-surfers-imitation/assets/1050880/2f900844-1ef8-48a8-8853-29c4ad529251)
And change SyboGames.com to Spirit45 Game Studio ( https://spirit45.io)

**Comment by ahsan2607** [comment]
![Screenshot (401)](https://github.com/ahsan2607/subway-surfers-imitation/assets/103492143/018f60b7-ee57-4050-847b-91de4719755d)
Done
