### ISSUE TITLE
Add one more box for the content

### ISSUE THREAD

**Issue by tsanyqudsi** [ahsan2607/subway-surfers-imitation#9]
For now the last content box is character list, add one more below the box. Make it something like this for the layout.

![image](https://github.com/ahsan2607/subway-surfers-imitation/assets/1050880/91bff218-4d5b-40dc-87a3-fde7160524ea)

**Comment by ahsan2607** [comment]
![Screenshot (399)](https://github.com/ahsan2607/subway-surfers-imitation/assets/103492143/6ceeab85-5631-4af7-922d-3c08250f7c78)
Done
